--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "APP"."FLIGHT" (
		"ID" BIGINT NOT NULL,
		"ARRIVALDATE" DATE,
		"ARRIVALTIME" TIME,
		"DEPARTUREDATE" DATE,
		"DEPARTURETIME" TIME,
		"FLIGHTNR" VARCHAR(255),
		"AIRLINE_ID" BIGINT,
		"AIRPLANE_ID" BIGINT,
		"DESTINATION_ID" BIGINT,
		"ORIGIN_ID" BIGINT
	);

CREATE TABLE "APP"."AIRPORT" (
		"ID" BIGINT NOT NULL,
		"AIRPORTCODE" VARCHAR(255),
		"CITY" VARCHAR(255),
		"COUNTRY" VARCHAR(255),
		"NAME" VARCHAR(255)
	);

CREATE TABLE "APP"."AIRLINE" (
		"ID" BIGINT NOT NULL,
		"NAME" VARCHAR(255)
	);

CREATE TABLE "APP"."AIRPLANE" (
		"ID" BIGINT NOT NULL,
		"CAPACITY" INTEGER,
		"MODEL" VARCHAR(255),
		"SERIALNR" VARCHAR(255)
	);

CREATE TABLE "APP"."SEQUENCE" (
	);

ALTER TABLE "APP"."FLIGHT" ADD CONSTRAINT "SQL180617212928220" PRIMARY KEY ("ID");

ALTER TABLE "APP"."AIRPORT" ADD CONSTRAINT "SQL180617212928190" PRIMARY KEY ("ID");

ALTER TABLE "APP"."AIRLINE" ADD CONSTRAINT "SQL180617212928080" PRIMARY KEY ("ID");

ALTER TABLE "APP"."AIRPLANE" ADD CONSTRAINT "SQL180617212928160" PRIMARY KEY ("ID");

ALTER TABLE "APP"."FLIGHT" ADD CONSTRAINT "FLIGHTDSTINATIONID" FOREIGN KEY ("DESTINATION_ID")
	REFERENCES "APP"."AIRPORT" ("ID");

ALTER TABLE "APP"."FLIGHT" ADD CONSTRAINT "FLIGHT_AIRPLANE_ID" FOREIGN KEY ("AIRPLANE_ID")
	REFERENCES "APP"."AIRPLANE" ("ID");

ALTER TABLE "APP"."FLIGHT" ADD CONSTRAINT "FLIGHT_AIRLINE_ID" FOREIGN KEY ("AIRLINE_ID")
	REFERENCES "APP"."AIRLINE" ("ID");

ALTER TABLE "APP"."FLIGHT" ADD CONSTRAINT "FLIGHT_ORIGIN_ID" FOREIGN KEY ("ORIGIN_ID")
	REFERENCES "APP"."AIRPORT" ("ID");

